### ISSUE TITLE
No audio on DMR BrandMeister

### ISSUE THREAD

**Issue by cjeffcoat2** [Toysoft/OpenGD77-#1]
Hey, when I am on A DMR channel, and one person unkeys and the next person keys up quickly behind them, I do not hear audio, I can go into the menu and then leave the menu, and then the audio returns. It only happens on the gd77 I have a gd77s that doesn't seem to have this issue. The only way I was able to catch it is to have both radios on at the same time.￼. It does not happen all of the time.￼￼￼￼

**Comment by Toysoft** [comment]
Post on the original repository,

https://github.com/rogerclarkmelbourne/OpenGD77/ 

TS

**Comment by Toysoft** [comment]
Post on the original repository,

https://github.com/rogerclarkmelbourne/OpenGD77/ 

TS

**Comment by cjeffcoat2** [comment]
OK, thank you.
